import { Inter } from 'next/font/google'
import './globals.css'
import RecoilRootProvider from './recoilRootProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  )
}
